### ISSUE TITLE
Not compatible with VSCode 1.40.2

### ISSUE THREAD

**Issue by PeterWone** [yezhiquan2007/PDFInspector#1]
Installation failed.

```
Unable to install 'k5hh.pdf' extension because it is not compatible with the current version of VS Code (version 1.40.2).
```

**Comment by yezhiquan2007** [comment]
I think you can update vscode to ^1.42.0.
1.42.0 is default lowest version setted by VS Code's Yeoman.

**Comment by yezhiquan2007** [comment]
> Installation failed.
> 
> ```
> Unable to install 'k5hh.pdf' extension because it is not compatible with the current version of VS Code (version 1.40.2).
> ```

I think you can update vscode to ^1.42.0.
1.42.0 is default lowest version setted by VS Code's Yeoman.

**Comment by PeterWone** [comment]
Well, that's embarrassing. I had autoupdate  disabled due to past problems with the Arduino extension. I've re-enabled it. Thanks.
